### ISSUE TITLE
Parse arguments

### ISSUE THREAD

**Issue by albertotn** [albertotn/github-action-sql-syntax-check#5]
In the main class, check if arguments are present, null or empty. If so, print out a small help text, otherwise parse them

**Comment by dip77** [comment]
hi @albertotn, can you assign this to me?

**Comment by albertotn** [comment]
Sure! Assigned, please be sure to test it before doing PR, ask for any question

**Comment by albertotn** [comment]
Closed, thanks for your contribution!
